### ISSUE TITLE
[Patterns] Most previously pattern examples are running into conflict / missing component type definitions

### ISSUE THREAD

**Issue by MarioArriaga92** [meshery/meshery#5002]
#### Current Behavior

Most previously pattern examples are running into conflict / missing component type definitions

#### Expected Behavior

Pattern files defined in [service-mesh-patterns/service-mesh-patterns](https://github.com/service-mesh-patterns/service-mesh-patterns/tree/master/samples) should not fail deployment

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup create a pattern. Try to deploy it. See that the component type is unrecognized. e.g. Type: `Gateway.Istio` is not recognized.

**Comment by leecalcote** [comment]
@Revolyssup try to apply any of the sample patterns that we have published.

**Comment by Revolyssup** [comment]
@leecalcote  Fixed by latest meshkit release

**Comment by MarioArriaga92** [comment]
@leecalcote @Revolyssup is meshkit obtained dynamically or should we create a new release candidate for meshery v.0.6.0?

**Comment by MarioArriaga92** [comment]
checks for PR whose branch where e2e cypress test for this functionality exist are [running](https://github.com/meshery/meshery/runs/5071465910?check_suite_focus=true) right now but wanted to see if there's any update I'd need to do locally if I wanted to run them on my machine **(maybe update the application/pattern samples used?)**

**Comment by MarioArriaga92** [comment]
Still failing 😢 
![Screen Shot 2022-02-04 at 13 24 04](https://user-images.githubusercontent.com/23443575/152590535-4cc2460a-5f29-40d3-b85e-0c963fa48f0a.png)

**Comment by MarioArriaga92** [comment]
Files used are [this IstioFilterPattern file](https://github.com/meshery/meshery/blob/ae253eba9c79677882c91210199ccd21fa18fee8/ui/cypress/fixtures/configuration/service-mesh-patterns-samples/IstioFilterPattern-commit-b23b219.yaml) and this [BookInfoPattern file](https://github.com/meshery/meshery/blob/ae253eba9c79677882c91210199ccd21fa18fee8/ui/cypress/fixtures/configuration/service-mesh-patterns-samples/bookInfoPattern-commit-5eb2369.yaml)

**Comment by MarioArriaga92** [comment]
Here's error for [IstioFilterPattern file](https://github.com/meshery/meshery/blob/ae253eba9c79677882c91210199ccd21fa18fee8/ui/cypress/fixtures/configuration/service-mesh-patterns-samples/IstioFilterPattern-commit-b23b219.yaml):
`"Failed to deploy pattern file: rpc error: code = Unknown desc = no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"`

Screenshot:
<img width="954" alt="Screen Shot 2022-02-04 at 13 35 01" src="https://user-images.githubusercontent.com/23443575/152592013-4767c5ec-7902-4cb0-9567-9911453c1146.png">
